# Generated by Django 4.2.7 on 2025-10-31 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_app', '0001_initial'),
        ('payement_app', '0001_initial'),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='paiements',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relat_paye', to='payement_app.paiement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.panier'),
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='Panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.panier'),
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.products'),
        ),
    ]
