# Generated by Django 4.2.7 on 2025-10-31 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('stripe', 'Carte Bancaire'), ('ligdicash', 'Mobile Money')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statu', models.CharField(choices=[('en_attente', 'Attente'), ('reussi', 'Reussi'), ('echec', 'Echoué'), ('annule', 'Annule')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('stripe_payement_intent_id', models.CharField(blank=True, max_length=100)),
                ('ligdicash_transaction_id', models.CharField(blank=True, max_length=100)),
                ('ligdicash_phone', models.CharField(blank=True, max_length=20)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relat_cmd', to='order_app.commande')),
            ],
        ),
    ]
