# Generated by Django 4.2.7 on 2025-10-31 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('ordre', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pourcentage', models.IntegerField(default=0)),
                ('icone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PreuveSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='preuves/')),
                ('date_obtention', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reputation_app.categoriepreuve')),
            ],
        ),
    ]
