# Generated by Django 4.2.7 on 2025-10-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('stock_reserve', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_on_promo', models.BooleanField(default=False)),
            ],
        ),
    ]
